lab_1/urls.py
from django.conf.urls import url
from .views import index
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
]

lab_7/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
	url(r'^$', index, name='index'),
	url(r'^add-friend/$', add_friend, name='add-friend'),
	url(r'^validate-npm/$', validate_npm, name='validate-npm'),
	url(r'^delete-friend/$', delete_friend, name='delete-friend'),
	url(r'^get-friend-list/$', friend_list, name='get-friend-list'),
	url(r'^friends/$', getFriendList, name='all'),
	url(r'display-friend/(?P<pk>[0-9]+)/$', displayBio, name='display-friend'),
]

praktikum/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import lab_1.urls as lab_1
import lab_2.urls as lab_2
import lab_2_addon.urls as lab_2_addon
#from lab_1.views import index as index_lab1
#from lab_2.views import index as index_lab2
import lab_3.urls as lab_3
import lab_4.urls as lab_4
import lab_5.urls as lab_5
import lab_6.urls as lab_6
import lab_7.urls as lab_7
import lab_8.urls as lab_8
import lab_9.urls as lab_9
import lab_10.urls as lab_10

from django.views.generic.base import RedirectView


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^lab-1/', include(lab_1,namespace='lab-1')),
    url(r'^lab-2/', include(lab_2,namespace='lab-2')),
    url(r'^lab-2-addon/', include(lab_2_addon,namespace='lab-2-addon')),
    url(r'^lab-3/', include(lab_3,namespace='lab-3')),
    url(r'^lab-4/', include(lab_4,namespace='lab-4')),
    url(r'^lab-5/', include(lab_5, namespace='lab-5')),
    url(r'^lab-6/', include(lab_6,namespace='lab-6')),
    url(r'^lab-7/', include(lab_7,namespace='lab-7')),
    url(r'^lab-8/', include(lab_8,namespace='lab-8')),
    url(r'^lab-9/', include(lab_9,namespace='lab-9')),
    url(r'^lab-10/', include(lab_10,namespace='lab-10')),
    url(r'^$', RedirectView.as_view(url='/lab-4/', permanent = 'True'), name='index'),
]

lab_7/models.py
from django.db import models

class Friend(models.Model):
	friend_name = models.CharField(max_length=400)
	npm = models.CharField(max_length=250)
	alamat = models.CharField(max_length=400, default="-")
	ttl = models.CharField(max_length=400, default="-")
	prodi = models.CharField(max_length=100, default="-")
	added_at = models.DateField(auto_now_add=True)

lab_7/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.core import serializers
from django.db.models.fields.related import ManyToManyField
from .models import Friend
from Packages.api_csui_helper.csui_helper import CSUIhelper
import os
import json

response = {}
csui_helper = CSUIhelper(os.environ.get("SSO_USERNAME"),
                         os.environ.get("SSO_PASSWORD"))

def index(request):
    # Page halaman menampilkan list mahasiswa yang ada
    # TODO berikan akses token dari backend dengan menggunakaan helper yang ada
	auth = csui_helper.instance.get_auth_param_dict()
	mahasiswa_list = csui_helper.instance.get_mahasiswa_list()
	friend_list = Friend.objects.all()
	response = {"mahasiswa_list": mahasiswa_list, "friend_list": friend_list, "access_token": auth['access_token'], "client_id": auth["client_id"]}
	html = 'lab_7/lab_7.html'
	return render(request, html, response)

def friend_list(request):
	friend_list = Friend.objects.all()
	response['friend_list'] = friend_list
	response['access_token'] = csui_helper.instance.get_auth_param_dict()['access_token']
	response['client_id'] = csui_helper.instance.get_auth_param_dict()['client_id']
	html = 'lab_7/daftar_teman.html'
	return render(request, html, response)

def getFriendList(request):
	list = Friend.objects.all()
	hasil = []
	for x in list:
		hasil.append(to_dict(x))
	return JsonResponse({'daftar':hasil})

@csrf_exempt
def add_friend(request):
	if request.method == 'POST':
		name = request.POST['name']
		npm = request.POST['npm']
		alamat = request.POST.get('alamat')
		ttl = request.POST.get('ttl')
		prodi = request.POST.get('prodi')
		isValid = npmValid(npm)
		data = {'valid':isValid}
		if isValid:
			friend = Friend(friend_name=name, npm=npm, alamat=alamat, ttl=ttl, prodi=prodi)
			friend.save()
			data['teman'] = to_dict(friend)
		return JsonResponse(data)

@csrf_exempt
def delete_friend(request):
    if request.method == 'POST':
        friend_id = request.POST['friend_id']
        Friend.objects.filter(id=friend_id).delete()
        selector = '#'+friend_id
        data = {'selector':selector}
        return JsonResponse(data)

@csrf_exempt
def validate_npm(request):
    npm = request.POST.get('npm', None)
    isAda = not npmValid(npm);
    data = {
        'is_taken': isAda
    }
    return JsonResponse(data)

def to_dict(instance):
	opts = instance._meta
	data = {}
	for f in opts.concrete_fields + opts.many_to_many:
		data[f.name] = f.value_from_object(instance)
	return data


def npmValid(npm):
	allFriend = Friend.objects.all()
	for x in allFriend :
		if x.npm == npm:
			return False
	return True

def displayBio(request, pk):
    html = 'lab_7/biodata.html'
    response['teman'] = Friend.objects.filter(id=pk)[0]
    return render(request, html, response)

lab_7/templates/lab_7/biodata.html
{% extends "lab_7/layout/base.html" %}

{% block content %}
<section name="friend-list" class="friend-list">
    <div class="container">
        <div class="row">
        	<div class="col-md-8 col-lg-12">
        		<h2>{{ teman.friend_name }} </h2>
        	</div>
            <div class="col-md-8 col-lg-12">
                <table width="100%">
	                <tr>
	                	<td><h4>NPM</h4></td>
	                	<td><h4>{{ teman.npm }}</h4></td>
	                </tr>
	                <tr>
	                	<td><h4>Prodi</h4></td>
	                	<td><h4>{{ teman.prodi }}</h4></td>
	                </tr>
	                <tr>
	                	<td><h4>TTL</h4>
	                	<td><h4>{{ teman.ttl }}</h4></td>
	                </tr>
	                <tr>
	                	<td><h4>Alamat</h4></td>
	                	<td><h4 id="address">{{ teman.alamat }}</h4></td>
            		</tr>
            	</table>
            </div>
        </div>
        <div class="container">
        	<div id="googleMap" style="width:300px; height:200px; margin: 50px 0"></div>
        </div>
        <div>
        </div>
</section>
{% endblock %}
{% block javascript %}
<script>
	console.log($("#address").text());
	var address = $("#address").text();

	function initMap() {
		var geocoder = new google.maps.Geocoder();
		geocoder.geocode({'address': address}, function(results, status) {
			if (status === google.maps.GeocoderStatus.OK) {
				var propertiPeta = {
					center: results[0].geometry.location,
					zoom: 15,
					mapTypeId: google.maps.MapTypeId.ROADMAP
				};
				var peta = new google.maps.Map(document.getElementById("googleMap"), propertiPeta);
				var marker = new google.maps.Marker({
				  map: peta,
				  position: results[0].geometry.location
				});
			} else {
				var html = '<div class="alert alert-danger text-center">\
                            	Lokasi tidak ditemukan!\
                            </div>';
                $("#googleMap").append(html)
			}
		});
	}
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCLthXcNO7WAlfzjti3VdqgMVOaLZdrbCk&callback=initMap"async defer></script>
{% endblock %}

lab_7/templates/lab_7/daftar_teman.html
{% extends "lab_7/layout/base.html" %}

{% block content %}
    <section name="friend-list" id="friend-list">
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-lg-8">
                    <h2> friend Fasilkom</h2>
                    <div id="friend-list" class="list-group">

                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}
{% block javascript %}
    <script>
        $( document ).ready(function () {
            {# lengkapi pemanggilan ajax berikut untuk mengambil daftar teman yang ada di database #}
            $.ajax({
                method: "GET",
                url: '{% url "lab-7:all" %}',
                dataType: 'json',
                success: function (response) {
        					daftar = response['daftar'];
        					for(i=0; i<daftar.length; i++){
								container = '<div style="margin-bottom:20px;" id='+daftar[i].id+'>';
        						html = '<a class="list-group-item clearfix" onclick="displayFriend('+daftar[i].id+');">' +
        							daftar[i].friend_name + ' (' +
        							daftar[i].npm
        							+ ') </a>';
								button = '<button class="buttonDelete" onClick=deleteFriend('+daftar[i].id+')>DELETE</button>';
        						$("#friend-list").append(container+html+button+'</div>');
        					}
                },
                error: function(error){
                    {#tampilkan pesan error#}
                }
            });

      });
      var deleteFriend = function(id) {
        $.ajax({
          method: "POST",
          url : "{% url 'lab-7:delete-friend' %}",
          data: {friend_id:id},
          dataType : 'json',
          success: $('#'+id).fadeOut(),
        });
      };

	  var displayFriend = function(id) {
      window.location.href = "display-friend/"+id;
	  };
    </script>
{% endblock %}

lab_7/templates/lab_7/lab_7.html
{% extends "lab_7/layout/base.html" %}
{% block content %}
<section name="mahasiswa-list" id="mahasiswa-list">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-lg-8">
                <h2> Mahasiswa Fasilkom</h2>
                {% for i in "xxxxxxxxxx" %}
                    {% widthratio forloop.counter0 1 10 as a  %}
                    {% widthratio forloop.counter 1 10 as b %}
                    {% with a|stringformat:"s" as awal %}
                    {% with b|stringformat:"s" as akhir %}
                    {% with ":"|add:b as pertama %}
                    {% with awal|add:pertama as lolo %}
                    <div class="list-group{{ forloop.counter }}">
                            {% if mahasiswa_list|slice:lolo %}
                                {% for mahasiswa in mahasiswa_list|slice:lolo %}
                                    <a class="list-group-item clearfix">
                                        {{ mahasiswa.nama }} ({{ mahasiswa.npm }})
                                        <span class="pull-right">
                                          <span class="btn btn-xs btn-default" onClick="addFriend('{{ mahasiswa.nama }}', '{{ mahasiswa.npm }}', '{{ mahasiswa.alamat_mhs }}', '{{ mahasiswa.kota_lahir }}, {{ mahasiswa.tgl_lahir }}', '{{ mahasiswa.program.0.nm_org }} ({{ mahasiswa.program.0.nm_prg }})')">
                                            Tambah sebagai teman
                                          </span>
                                        </span>
                                    </a>
                                {% endfor %}
                            {% else %}
                                <div class="alert alert-danger text-center">
                                    <strong>Opps!</strong> Tidak ada mahasiswa
                                </div>
                            {% endif %}
                    </div>
                  {% endwith %}
                  {% endwith %}
                  {% endwith %}
                  {% endwith %}
                {% endfor %}
                <div style="text-align:center;width:100%;">
                  <div class="pagination" style="display:inline-block;"></div>
                </div>
            </div>
            <div class="col-lg-4">
                <h2> Teman Saya </h2>
                <div class="list-group" id="friend-list">
                    {% if friend_list %}
                        {% for friend in friend_list %}
                            <a class="list-group-item clearfix">
                                {{ friend.friend_name }} ({{ friend.npm }})
                            </a>
                        {% endfor %}
                    {% else %}
                        <div class="alert alert-danger text-center" id="alertin">
                            <strong>Opps!</strong> Tidak ada teman
                        </div>
                    {% endif %}
                </div>
                <form id="add-friend" action="#">
                    {% csrf_token %}
                    <label for="field_npm">npm</label>
                    <input id="field_npm" type="text" name="npm" class="form-control"/>
                    <label for="field_name">name</label>
                    <input id="field_name" type="text" name="name" class="form-control"/>
                    <button type="submit">Tambah</button>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}
{% block javascript %}
<script>
  $(document).ready(function(){
    for(i=1;i<11;i++){
      if(i!=1){
        $('.list-group'+i).hide();
      }
     // $('.pagination').append('<button class="abcd" onClick=next('+i+')>'+i+'</button>');

    }
  });

  var next = function(id){
    $('.list-group'+id).fadeIn();
    for(i=1;i<11;i++){
      if(i!=id){
        $('.list-group'+i).hide();
      }
    }

  };

 var addFriend = function(nama, npm, alamat, ttl, prodi) {
     $.ajax({
         method: "POST",
         url: "{% url "lab-7:add-friend" %}",
         data: {name: nama, npm: npm, alamat: alamat, ttl: ttl, prodi: prodi},
         success : function (friend) {
             if (friend.valid){
               html = '<a class="list-group-item clearfix">' +
                 friend.teman.friend_name + ' (' +
                 friend.teman.npm
                 + ') </a>';
               $("#friend-list").append(html).show('slow');
               $("#alertin").hide();
             } else {
               alert("Mahasiswa tersebut sudah ditambahkan sebagai teman")
             }
         },
         error : function (error) {
             alert("error")
         }
     });
 };

 $("#add-friend").on("submit", function () {
    name = $("#field_name").val()
    npm = $("#field_npm").val()
    addFriend(name, npm, '', '', '')
    event.preventDefault();
 });

 $("#field_npm").change(function () {
     console.log( $(this).val() );
     npm = $(this).val();
     $.ajax({
         method: "POST",
         url: '{% url "lab-7:validate-npm" %}',
         data: {
             'npm': npm
             },
             dataType: 'json',
             success: function (data) {
                 console.log(data)
                 if (data.is_taken) {
                     alert("Mahasiswa dengan npm seperti ini sudah ada");
                 }
             }
         });
     });
 </script>
{% endblock %}